### ISSUE TITLE
Problème de récupération de flux RSS

### ISSUE THREAD

**Issue by sbenmansour** [jeedom/plugin-weather#12]
Bonjour,
J'avais le plugin installé et parfaitement fonctionnel.
Puis, dernièrement, j'ai désinstallé puis réinstallé le plugin après quelques jours.
Depuis, le widget sur le dashboard n'affiche plus rien, et j'ai l'impression que le cron ne s'exécute plus. La programmation du cron affiche "00 05 02 04 * 2016", et même si je la modifie manuellement pour mettre une fréquence de 5 min par exemple, elle se remet à cette valeur.
Il n'y a aucune trace dans le log cron à part les logs de backup.

Y a-t-il moyen de debugger en exécutant la commande manuellement, pour voir ce qui ne va pas ?

Il est à noter que j'ai une installation custom, sur une Raspberry Pi 2, que j'ai réalisée en suivant le guide dans la doc officielle.

**Comment by sbenmansour** [comment]
Je me rends compte en jetant un oeil sur le code que le cron gère les événements sunrise et sunset :)

Yahoo Weather ont modifié leur API, et le RSS n'est plus disponible sur http://weather.yahooapis.com/forecastrss
Il faut le modifier par http://xml.weather.yahoo.com/forecastrss
Ça a marché chez moi et mon widget s'est mis à jour.

Je change le sujet du ticket.

**Comment by zoic21** [comment]
On a changé le provider.
