### ISSUE TITLE
Atmospheric pressure is not expressed at Sea level

### ISSUE THREAD

**Issue by diving91** [jeedom/plugin-weather#5]
To have the atmospheric pressure expressed at sea level, it is needed to enter a correction. This plugin does not allow to enter value correction (#value# + x) to get the atmospheric pressure at Sea level

**Comment by zoic21** [comment]
Hi,
This data is from yahoo, I can not change it

**Comment by diving91** [comment]
Hi,

I know this comes from yahoo, but within the plugin, can't you add the ability to change this specific value (by adding an offset)?
For other plugins, it is eg possible to add an offset to a Temperature sensors

My understanding is that the ability to add an offset is not realted to yahoo, but to Jeedom itself

kind regards

----- Mail original -----
De: "Loïc" <notifications@github.com>
À: "jeedom/plugin-weather" <plugin-weather@noreply.github.com>
Cc: "diving91" <avhs@free.fr>
Envoyé: Dimanche 10 Mai 2015 14:35:00
Objet: Re: [plugin-weather] Atmospheric pressure is not expressed at Sea level (#5)



Hi, 
This data is from yahoo, I can not change it

**Comment by zoic21** [comment]
Did you try to add this offcet in advance command configuration ?

**Comment by diving91** [comment]
grrrr, I'm a really stupid Guy!
Yes it works fine
for some reason, before this call, I've not been able to find this (in 1.177 or earlier version the advanced command tab was not found by me for this plugin)
Sorry to bother you with this, my fault!

----- Mail original -----
De: "Loïc" <notifications@github.com>
À: "jeedom/plugin-weather" <plugin-weather@noreply.github.com>
Cc: "diving91" <avhs@free.fr>
Envoyé: Dimanche 10 Mai 2015 15:31:44
Objet: Re: [plugin-weather] Atmospheric pressure is not expressed at Sea level (#5)



Did you try to add this offcet in advance command configuration ?

**Comment by diving91** [comment]
Coming back on this. Since I added #value# + 11 in advance command configuration, the value is freezed at the value that was available at that moment.
In cache db, I see that the collectDate is changing (last one {"collectDate":"2015-05-13 08:30:04"}), but the value itself not.
In the dashboard widget, I see the collectDate, but with a fixed value.
Since Value is 1026.92 I doubt that the Patm is stable with 2 digit accuracy. Also real Patm has shifted for about 7mb so that yahoo has almost for sure updated its value

Is this a possible bug?
Herve

----- Mail original -----
De: avhs@free.fr
À: "jeedom/plugin-weather" <reply@reply.github.com>
Envoyé: Dimanche 10 Mai 2015 15:47:16
Objet: Re: [plugin-weather] Atmospheric pressure is not expressed at Sea level (#5)

grrrr, I'm a really stupid Guy!
Yes it works fine
for some reason, before this call, I've not been able to find this (in 1.177 or earlier version the advanced command tab was not found by me for this plugin)
Sorry to bother you with this, my fault!

----- Mail original -----
De: "Loïc" <notifications@github.com>
À: "jeedom/plugin-weather" <plugin-weather@noreply.github.com>
Cc: "diving91" <avhs@free.fr>
Envoyé: Dimanche 10 Mai 2015 15:31:44
Objet: Re: [plugin-weather] Atmospheric pressure is not expressed at Sea level (#5)



Did you try to add this offcet in advance command configuration ?
