### ISSUE TITLE
Problème affichage du dashboard

### ISSUE THREAD

**Issue by lennvilardi** [jeedom/plugin-weather#7]
Bonjour,
Quand j'active le plugin météo en stable ou en beta, et que je le rends visible sur le dashboard, le dashboard n'affiche qu'un widget et les menus comportent des {{ et des }} en plus.
![2015-10-31 19_05_21-dashboard - jeedom](https://cloud.githubusercontent.com/assets/10863269/10865146/6ee87736-8002-11e5-96d4-5ad24970d666.png)

**Comment by zoic21** [comment]
Bonjour,
A mon avis ton jeedom n'est pas en dernière version, merci de le mettre a jour pour corriger

**Comment by lennvilardi** [comment]
Au temps pour moi, merci de m'avoir apporté la solution :)
