### ISSUE TITLE
Valeurs à 0 si erreur de récupération

### ISSUE THREAD

**Issue by eliovir** [jeedom/plugin-weather#8]
Je coupe mon accès Internet lorsque je ne suis pas chez moi.

Weather est configuré pour récupérer toutes les 30 minutes les données.

Quand l'accès est coupé, les valeurs (température, pression, vitesse du vent, humidité) sont tout de même enregistrées avec 0.

L'historique ne devrait pas contenir de valeurs pour ces périodes.

**Comment by zoic21** [comment]
Salut,
La derniere beta du plugin corrige ce soucis
